### ISSUE TITLE
File bug for Invalid Unicode An invalid XML character (Unicode: 0x16)

### ISSUE THREAD

**Issue by jpasski** [OpenSemanticsIO/semiotics-main#22]
Root exception:
java.lang.RuntimeException: An invalid XML character (Unicode: 0x16) was found in the element content:\u0016FooBar
  at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl$Escape.convert(XMLSaveImpl.java:3342)
  at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.getDatatypeValue(XMLSaveImpl.java:3113)
  at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveDataTypeSingle(XMLSaveImpl.java:1698)
  at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveFeatures(XMLSaveImpl.java:1280)
  at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveFeatures(XMLSaveImpl.java:1224)
  at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElementID(XMLSaveImpl.java:2716)
  at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElement(XMLSaveImpl.java:1181)
  at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElement(XMLSaveImpl.java:1042)
  at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveContainedSingle(XMLSaveImpl.java:2403)
  at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveFeatures(XMLSaveImpl.java:1547)
  at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveFeatures(XMLSaveImpl.java:1224)
  at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.saveElementID(XMLSaveImpl.java:2716)
  at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.writeTopObject(XMLSaveImpl.java:683)
  at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.traverse(XMLSaveImpl.java:591)
  at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.save(XMLSaveImpl.java:251)
  at org.eclipse.emf.emfstore.internal.server.model.versioning.impl.FileBasedChangePackageImpl.add(FileBasedChangePackageImpl.java:520)
  at org.eclipse.emf.emfstore.internal.server.model.versioning.impl.FileBasedChangePackageImpl.addAll(FileBasedChangePackageImpl.java:494)
  at org.eclipse.emf.emfstore.internal.client.model.impl.ProjectSpaceBase.addOperations(ProjectSpaceBase.java:214)
  at org.eclipse.emf.emfstore.internal.client.model.impl.OperationManager.operationsRecorded(OperationManager.java:156)
  at org.eclipse.emf.emfstore.internal.client.model.impl.OperationRecorder.operationsRecorded(OperationRecorder.java:306)
  at org.eclipse.emf.emfstore.internal.client.model.impl.OperationRecorder.commandCompleted(OperationRecorder.java:523)
  at org.eclipse.emf.emfstore.internal.client.model.impl.OperationRecorder.commandCompleted(OperationRecorder.java:471)
  at org.eclipse.emf.emfstore.internal.client.model.impl.OperationManager.commandCompleted(OperationManager.java:205)
  at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at org.eclipse.emf.emfstore.internal.common.observer.ObserverBus$ProxyHandler.notifiyObservers(ObserverBus.java:309)
  at org.eclipse.emf.emfstore.internal.common.observer.ObserverBus$ProxyHandler.invoke(ObserverBus.java:277)
  at com.sun.proxy.$Proxy23.commandCompleted(Unknown Source)
  at org.eclipse.emf.emfstore.internal.client.model.changeTracking.commands.EMFStoreCommandNotifier.notifiyListenersAboutCommandCompleted(EMFStoreCommandNotifier.java:72)
  at org.eclipse.emf.emfstore.internal.client.model.changeTracking.commands.EMFStoreBasicCommandStack.execute(EMFStoreBasicCommandStack.java:79)
  at org.eclipse.emf.emfstore.internal.client.model.util.AbstractEMFStoreCommand.aRun(AbstractEMFStoreCommand.java:108)
  at org.eclipse.emf.emfstore.internal.client.model.util.EMFStoreCommand.run(EMFStoreCommand.java:60)
  at org.eclipse.emf.emfstore.internal.client.importexport.ExportImportControllerExecutor.execute(ExportImportControllerExecutor.java:73)
  at org.eclipse.emf.ecp.emfstore.internal.ui.handler.ExportProjectHelper.exportProject(ExportProjectHelper.java:71)
  at org.eclipse.emf.ecp.emfstore.internal.ui.handler.ExportProjectHandler.execute(ExportProjectHandler.java:41)
  at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
  at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
  at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
  at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
  at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
  at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
  at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
  at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
  at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
  at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
  at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:799)
  at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:675)
  at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$7(HandledContributionItem.java:659)
  at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:592)
  at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
  at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
  at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
  at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
  at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
  at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
  at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
  at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
  at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
  at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
  at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
  at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
  at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
  at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
  at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
  at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
  at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
  at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
  at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
  at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
  at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
  at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
  at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
  at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
  at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

**Comment by jpasski** [comment]
Tracking now via [forum post](https://www.eclipse.org/forums/index.php?t=msg&th=1076858&goto=1730321&#msg_1730321) and [bug 492471](https://bugs.eclipse.org/bugs/show_bug.cgi?id=492471)
