### ISSUE TITLE
Add org.eclipse.equinox.log to bundles

### ISSUE THREAD

**Issue by jpasski** [OpenSemanticsIO/semiotics-main#35]
Obscure exception:

```
Exception in thread "Thread-2" java.lang.NullPointerException
  at org.eclipse.core.internal.runtime.InternalPlatform.getLog(InternalPlatform.java:353)
  at org.eclipse.core.runtime.Platform.getLog(Platform.java:1017)
  at org.eclipse.emf.emfstore.internal.server.EMFStoreController.initLogging(EMFStoreController.java:238)
  at org.eclipse.emf.emfstore.internal.server.EMFStoreController.run(EMFStoreController.java:142)
  at org.eclipse.emf.emfstore.internal.server.EMFStoreController.run(EMFStoreController.java:566)
  at java.lang.Thread.run(Thread.java:745)
```

`org.eclipse.core.internal.runtime.InternalPlatform.getLog(Bundle)`:

```
public ILog getLog(Bundle bundle) {
  Log result = logs.get(bundle);
  if (result != null)
    return result;
  ExtendedLogService logService = extendedLogTracker.getService();
  Logger logger = logService == null ? null : logService.getLogger(bundle, PlatformLogWriter.EQUINOX_LOGGER_NAME);
  result = new Log(bundle, logger);
  ExtendedLogReaderService logReader = logReaderTracker.getService();
  logReader.addLogListener(result, result);
  logs.put(bundle, result);
  return result;
}
```

ExtendedLogService lives in `org.eclipse.equinox.log`

**Comment by jpasski** [comment]
Worked (after including `org.osgi.service.event` as a run bundle
